### ISSUE TITLE
[Client] Routing

### ISSUE THREAD

**Issue by JaeHeon-Kim** [codestates/mindcaptor-client#24]
### ISSUE
- Group:  `client`
- Type: `routing`
- Detail: rout pages

### TODO
1. [x] 로그인, 게스트 -> 대기방 연결
2. [x] 대기방 -> 마이페이지 연결
3. [x] 대기방 게임참여 -> 인게임
4. [x] 대기방 방 만들기 -> 새로운 게임 방
5. [x] 대기방 로그아웃 -> 메인페이지

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Completed time: `C: 1h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
